dotNET.MURAT.GRANET/ASPJalon3/Controllers/EmployeController.cs
using System.Linq;
using System.Web.Mvc;
using BusinessLogicLayer;
using BusinessLogicLayer.Queries;

namespace ASPjalon3.Controllers
{
    public class EmployeController : Controller
    {
        private readonly Manager _manager;

        public EmployeController()
        {
            _manager = Manager.Instance();
        }

        public ActionResult Index()
        {
            var employes = _manager.GetAllEmploye();
            return View(employes);
        }

        public ActionResult Details(int id)
        {
            var employe = _manager.GetByIDEmploye(id);
            if (employe == null)
            {
                return HttpNotFound("Employé non trouvé");
            }
            return View(employe);
        }

        public ActionResult Search(string searchTerm)
        {
            var employes = _manager.SearchEmploye(searchTerm);
            return View("Index", employes);
        }
    }
}

dotNET.MURAT.GRANET/ASPJalon3/Controllers/OffreController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Bibliotheque.Entity;
using BusinessLogicLayer;
using BusinessLogicLayer.Queries;

namespace ASPjalon3.Controllers
{
    public class OffreController : Controller
    {
        private readonly Manager _manager;

        public OffreController()
        {
            _manager = Manager.Instance();
        }

        public ActionResult Index()
        {
            var offres = _manager.GetAllOffres();
            return View(offres);
        }

        public ActionResult Details(int id)
        {
            var offre = _manager.GetByIDOffre(id);
            if (offre == null)
            {
                return HttpNotFound("Offre non trouvée");
            }
            return View(offre);
        }

        public ActionResult Search(string searchTerm)
        {
            var offres = _manager.SearchOffre(searchTerm);
            return View("Index",offres);
        }
    }
}

dotNET.MURAT.GRANET/ASPJalon3/Controllers/PostulationController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Bibliotheque.Entity;
using BusinessLogicLayer;
using BusinessLogicLayer.Commands;
using BusinessLogicLayer.Queries;

namespace ASPjalon3.Controllers
{
    public class PostulationController: Controller
    {
        private readonly Manager _manager;
        
        public PostulationController()
        {
            _manager = Manager.Instance();
        }

        public ActionResult Postuler(int id)
        {
            var offre = _manager.GetByIDOffre(id);
            if (offre == null)
            {
                return HttpNotFound("Offre non trouvée");
            }
            var employeConnecte = _manager.GetByIDEmploye(1);

            if (employeConnecte != null)
            {
                var postulation = new Postulation
                {
                    OffreId = offre.Id,
                    EmployeId = employeConnecte.Id,
                    Date = DateTime.Now,
                    Statut = 1
                };

                _manager.AjouterPostulation(postulation);
                return RedirectToAction("Details", "Offre", new { id = offre.Id });

            }
            else
            {
                return HttpNotFound("Employé non trouvé");
            }
        }
        
        public ActionResult Index()
        {
            var employeConnecte = _manager.GetByIDEmploye(1);
            if (employeConnecte == null) return HttpNotFound("Employé non trouvé");
            var postulations = employeConnecte.Postulations;
            return View(postulations);
        }

    }
}

dotNET.MURAT.GRANET/ASPJalon3/Views/Employe/Details.cshtml
@model Bibliotheque.Entity.Employe

<h2>Détails de l'employé</h2>

<div>
    <h4>@Model.Nom, @Model.Prenom</h4>
    <p>Date de naissance: @Model.DateNaissance</p>
    <p>Ancienneté: @Model.Anciennete</p>
    <p>Biographie: @Model.Biographie</p>
    <p>Expériences:</p>
    <ul>
        @foreach (var experience in Model.Experiences)
        {
            <li> @experience.Intitule </li>
        }
    </ul>
    <p>Formations:</p>
    <ul>
        @foreach (var formation in Model.Formations)
        {
            <li> @formation.Intitule </li>
        }
    </ul>

</div>

<a href="@Url.Action("Index")">Retour à la liste des employés</a>

dotNET.MURAT.GRANET/ASPJalon3/Views/Employe/Index.cshtml
@model System.Collections.Generic.List<Bibliotheque.Entity.Employe>


<h1>Liste des employés</h1>

<h2>Rechercher un employé</h2>

<form method="get" action="@Url.Action("Search", "Employe")">
    <input type="text" name="searchTerm" value="" />
    <button type="submit">Rechercher</button>
</form>
@if (Model.Count == 0)
{
    <p>Aucun résultat trouvé.</p>
}
else
{
    <ul>
        @foreach (var employe in Model)
        {
            <li>
                <a href="@Url.Action("Details", new { id = employe.Id })">@employe.Nom, @employe.Prenom</a>
            </li>
        }
    </ul>
}

dotNET.MURAT.GRANET/ASPJalon3/Views/Offre/Details.cshtml
@model Bibliotheque.Entity.Offre
<h2>Détails de l'offre</h2>

<div>
    <h4>@Model.Intitule</h4>
    <p>Date: @Model.Date</p>
    <p>Salaire: @Model.Salaire</p>
    <p>Description: @Model.Description</p>
    <p>Responsable: @Model.Responsable</p>
    <p>Statut: @Model.Statut.Libelle</p>
    <p>Postulations:</p>
    <ul>
        @foreach (var postulation in Model.Postulations)
        {
            <li>
                <a href="@Url.Action("Details", "Employe", new { id = postulation.Employe.Id })">@postulation.Employe.Nom, @postulation.Employe.Prenom</a>
            </li>
        }
    </ul>
    <a href="@Url.Action("Postuler", "Postulation",new { id = Model.Id })">Postuler</a>
</div>

<a href="@Url.Action("Index")">Retour à la liste des offres</a>

dotNET.MURAT.GRANET/ASPJalon3/Views/Offre/Index.cshtml
@model System.Collections.Generic.List<Bibliotheque.Entity.Offre>

<h2>Liste des offres</h2>
<form method="get" action="@Url.Action("Search", "Offre")">
    <input type="text" name="searchTerm" value="" />
    <button type="submit">Rechercher</button>
</form>
@if (Model.Count == 0)
{
    <p>Aucun résultat trouvé.</p>
}
else
{
    <ul>
        @foreach (var offre in Model)
        {
            <li>
                <a href="@Url.Action("Details", new { id = offre.Id })">@offre.Intitule</a>
            </li>
        }
    </ul>
}

dotNET.MURAT.GRANET/ASPJalon3/Views/Postulation/Index.cshtml
@model System.Collections.Generic.ICollection<Bibliotheque.Entity.Postulation>

<h2>Postulations</h2>
<ul>
    @foreach (var postulation in Model)
    {
        <li>
            <a href="@Url.Action("Details", "Offre", new { id = postulation.Offre.Id })">@postulation.Offre.Intitule</a>
        </li>
    }
</ul>

dotNET.MURAT.GRANET/ASPJalon3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Offre", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Offre", "Index", "Offre")</li>
                <li>@Html.ActionLink("Employe", "Index", "Employe")</li>
                <li>@Html.ActionLink("Mes postulations", "Index", "Postulation")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.2023 - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>